server:
  port: 8081

spring:
  application:
    name: direct-exchange

  rabbitmq:
    host: 192.168.10.102
    port: 5672
    username: admin
    password: 520517li
    virtual-host: atkaien
myrabbit:
  exchangeName: exchange.direct
  queueAName: queue.direct.A
  queueBName: queue.direct.B
